[garage-1]
map = [
    "==================",
    "=^=[][]=.........=",
    "=.#....#.........=",
    "===--..=.........=",
    "..=....=.........=",
    "..=======#######==",
    "!!!!!!!!!!!!!!!!!!",
]
